[project]
name = "bou-ningen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=6.2.0",
    "mediapipe==0.10.9",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
]
